"""'init03'

Revision ID: b041e63868e3
Revises: bf8c66e884b3
Create Date: 2017-11-09 13:56:23.089000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b041e63868e3'
down_revision = 'bf8c66e884b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('st_history', sa.Column('register_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('st_history', 'register_date')
    # ### end Alembic commands ###
