"""'init02'

Revision ID: bf8c66e884b3
Revises: d36e804fd7fc
Create Date: 2017-11-09 11:41:27.408000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf8c66e884b3'
down_revision = 'd36e804fd7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sheet1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet1',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('catalog', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('part', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('desc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sn', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('purchase_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('create_user', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('create_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('modify_user', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('modify_date', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
