"""'init00'

Revision ID: d36e804fd7fc
Revises: 
Create Date: 2017-11-06 15:15:16.746000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36e804fd7fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_id'), 'catalog', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('storage',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('part', sa.String(length=30), nullable=True),
    sa.Column('sn', sa.String(length=40), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(precision=16, asdecimal=2), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('create_user', sa.String(length=30), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_user', sa.String(length=30), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_id'), 'storage', ['id'], unique=False)
    op.create_index(op.f('ix_storage_part'), 'storage', ['part'], unique=False)
    op.create_index(op.f('ix_storage_sn'), 'storage', ['sn'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('st_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('create_user', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_st_history_username'), 'st_history', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_st_history_username'), table_name='st_history')
    op.drop_table('st_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_storage_sn'), table_name='storage')
    op.drop_index(op.f('ix_storage_part'), table_name='storage')
    op.drop_index(op.f('ix_storage_id'), table_name='storage')
    op.drop_table('storage')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_catalog_id'), table_name='catalog')
    op.drop_table('catalog')
    # ### end Alembic commands ###
